const fs = require("fs");
const path = require("path");
const entities = require("entities");

const specificReplacements = {
  "<<string>>": "`string`",
  "<<String>>": "`String`",
  "<<Object>>": "`Object`",
  "<<object>>": "`object`",
  "<<integer>>": "`integer`",
  "<<Integer>>": "`Integer`",
};

// Function to capitalize the first letter of a string
const capitalizeFirstLetter = (string) => {
  return string.charAt(0).toUpperCase() + string.slice(1);
};

// Function to process special case
function processSpecialCase(line) {
  const match = line.match(/(.*?)(_.*?_)(.*)/);
  if (match) {
    const [_, part1, part2, part3] = match;
    return `${part1}${part2}\n${part3}`;
  }
  return line;
}

// Function to update the AsciiDoc file
const updateAsciiDoc = (filePath) => {
  const context = path.basename(fileName, path.extname(fileName));
  // Read the file
  fs.readFile(filePath, "utf8", (err, data) => {
    if (err) {
      console.error(`Error reading file: ${err}`);
      return;
    }

    // Split the content into lines
    const lines = data.split("\n");
    const updatedLines = [];
    let skipLines = true;
    let nextHeadingIsMainHeading = false;
    let capturedTitle = false;
    let documentTitle = "";

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();

      // Skip lines until we find '== Endpoints'
      if (skipLines) {
        if (line === "== Endpoints") {
          skipLines = false;
          continue; // Skip this line
        }
        continue; // Skip all lines before '== Endpoints'
      }

      // Skip lines with comments
      if (line.startsWith("//")) {
        continue; // Skip this line
      }

      // Stop processing when we encounter '[#models]'
      if (line.startsWith("[#models]")) {
        updatedLines.push('[id="common-object-reference_{context}"]');
        updatedLines.push("== Common object reference");
        updatedLines.push("");
        for (let j = i + 2; j < lines.length; j++) {
          let decodedLine = entities.decodeHTML(lines[j]);

          //replace \" with "
          if (decodedLine.includes('"')) {
            decodedLine = decodedLine.replace(/\"/g, '"');
          }

          // Check if the current line is "JSON" and skip it
          if (decodedLine.trim() === "JSON") {
            continue; // Skip this line
          }

          // Check if the next line is "====" and change it to "==== JSON representation"
          if (decodedLine.trim() === "====") {
            updatedLines.push("==== JSON representation");
            continue; // Skip adding the original "====" line
          }

          if (decodedLine.startsWith("[#")) {
            const updatedLine = decodedLine.replace(
              /\[(#)(.*)\]/g,
              (match, p1, p2) => {
                return `[id="${p2}_{context}"]`;
              }
            );
            updatedLines.push(updatedLine);
            continue;
          }

          // New case for updated lines starting with '=' and containing '_<some-text>_'
          if (decodedLine.startsWith("=") && /_[^_]+_/.test(decodedLine)) {
            decodedLine = processSpecialCase(decodedLine);
            updatedLines.push(decodedLine);
            continue;
          }

          if (decodedLine.includes("<<") && decodedLine.includes(">>")) {
            // Check for the specific edge case
            if (decodedLine.includes("<<Stream_result_of_")) {
              decodedLine = decodedLine.replace(
                /<<Stream_result_of_(.*?)>>/g,
                (match, p1) => {
                  // Capitalize the first letter of p1
                  const capitalizedP1 =
                    p1.charAt(0).toUpperCase() + p1.slice(1);
                  return `<<StreamResultOf${capitalizedP1}_{context}, Stream_result_of_${p1}>>`;
                }
              );
            } else {
              for (const [key, value] of Object.entries(specificReplacements)) {
                decodedLine = decodedLine.replace(new RegExp(key, "g"), value);
              }

              decodedLine = decodedLine.replace(/<<([^>]*)>>/g, (match, p1) => {
                return `<<${p1}_{context}, ${p1}>>`;
              });
            }

            updatedLines.push(decodedLine);
            continue;
          }
          updatedLines.push(decodedLine);
        }
        break;
      } else if (line.startsWith("[#models]") && fileName !== "index.adoc") {
        break;
      }

      // Add the auto-generated comment and content type at the beginning
      if (updatedLines.length === 0) {
        updatedLines.push("// Auto-generated by scripts. Do not edit.");
        updatedLines.push(":_mod-docs-content-type: ASSEMBLY");
        updatedLines.push(`:context: ${context}`);
        updatedLines.push("");
        nextHeadingIsMainHeading = true;
      }

      // Capitalize the first letter of lines starting with '[.'
      if (line.startsWith("[.") && capturedTitle) {
        let updatedLine = line.slice(2, -1).trim(); // Remove '[.' and trim spaces, then remove last character
        updatedLine = `[id="${capitalizeFirstLetter(updatedLine)}_{context}"]`
        //remove title from the line
        const newLine = updatedLine.replace(documentTitle, "").trim();
        if (newLine.length > 1) {
          updatedLine = newLine;
        }
        updatedLines.push(updatedLine); // Add the updated line
        continue;
      } else if (line.startsWith("[.") && !capturedTitle) {
        continue;
      }

      // If line starts with '=', check the number of '=' signs
      if (line.startsWith("=")) {
        if (!capturedTitle) {
          capturedTitle = true;
          //remove all spaces and `=` signs from the line
          documentTitle = line.replace(/[ =]/g, "");
          continue; //skip the title line
        }
        const equalCount = line.match(/^=+/)[0].length; // Count leading '=' signs
        if (equalCount > 3) {
          // Check if there are more than 2 '=' signs
          // Remove 3 '=' signs and trim spaces
          let updatedLine = line.slice(3).trim(); // Remove the first three '=' signs

          // Use regex to match the first word character after '== '
          updatedLine = updatedLine.replace(/(?:=\s)(\w)/, (match, p1) => {
            return `= ${p1.toUpperCase()}`; // Capitalize the first word character
          });

          //Remove document title from the line
          const newLine = updatedLine.replace(documentTitle, "").trim();
          if (newLine.length > 1) {
            updatedLine = newLine;
          }

          // New case for updated lines starting with '=' and containing '_<some-text>_'
          if (updatedLine.startsWith("=") && /_<[^_]+>_/.test(updatedLine)) {
            updatedLine = processSpecialCase(updatedLine);
          }

          updatedLines.push(updatedLine); // Add the updated line

          if (nextHeadingIsMainHeading) {
            updatedLines.push("");
            updatedLines.push(":toc: macro");
            updatedLines.push(":toc-title:");
            updatedLines.push("");
            updatedLines.push("toc::[]");
            updatedLines.push("");
            nextHeadingIsMainHeading = false;
          }
          continue;
        } else if (equalCount === 2) {
          // If there are exactly 2 '=', just trim the line
          let updatedLine = line.slice(2).trim();
          // New case for updated lines starting with '=' and containing '_<some-text>_'
          if (updatedLine.startsWith("=") && /_<[^_]+>_/.test(line)) {
            updatedLine = processSpecialCase(updatedLine);
          }
          updatedLines.push(updatedLine); // Add the updated line
          continue;
        }
      }

      // Check if line contains both <<some_text>> and add context to it <<some_text_{context}>>
      if (line.includes("<<") && line.includes(">>")) {
        let updatedLine = line;

        for (const [key, value] of Object.entries(specificReplacements)) {
          updatedLine = updatedLine.replace(new RegExp(key, "g"), value);
        }

        // Check for the specific edge case
        if (updatedLine.includes("<<Stream_result_of_")) {
          updatedLine = updatedLine.replace(
            /<<Stream_result_of_(.*?)>>/g,
            (match, p1) => {
              // Capitalize the first letter of p1
              const capitalizedP1 = p1.charAt(0).toUpperCase() + p1.slice(1);
              return `<<StreamResultOf${capitalizedP1}_{context}, Stream_result_of_${p1}>>`;
            }
          );
        } else {
          updatedLine = updatedLine.replace(/<<([^>]*)>>/g, (match, p1) => {
            return `<<${p1}_{context}, ${p1}>>`;
          });
        }
        updatedLines.push(updatedLine);
        continue;
      }

      // Check if line matches [#<some-text>] and change it to [id="<some-text>_{context}"]
      if (/$$#([^]]+)$$/.test(line)) {
        const updatedLine = line.replace(/$$#([^]]+)$$/g, (match, p1) => {
          return `[id="${p1}_{context}"]`;
        });
        updatedLines.push(updatedLine);
        continue;
      }

      // Push other lines unchanged
      updatedLines.push(line);
    }

    // Join the updated lines and write back to the file
    const updatedContent = updatedLines.join("\n");
    fs.writeFile(filePath, updatedContent, "utf8", (err) => {
      if (err) {
        console.error(`Error writing file: ${err}`);
      }
    });
  });
};

// Get the file name from command line arguments
const fileName = process.argv[2]; // The file name should be the second argument
if (!fileName) {
  console.error("Please provide the AsciiDoc file name as an argument.");
  process.exit(1);
}

// Specify the path to the AsciiDoc file
const filePath = path.join(__dirname, fileName); // Use the provided file name
//console.log(`Processing ${fileName}...`);
updateAsciiDoc(filePath);
