const fs = require("fs");
const path = require("path");
const entities = require("entities"); // For decoding HTML entities

// Predefined replacements for specific AsciiDoc inline formatting
const specificReplacements = {
  "<<string>>": "`string`",
  "<<String>>": "`String`",
  "<<Object>>": "`Object`",
  "<<object>>": "`object`",
  "<<integer>>": "`integer`",
  "<<Integer>>": "`Integer`",
};

// Function to capitalize the first letter of a string
const capitalizeFirstLetter = (string) => {
  if (typeof string !== 'string' || string.length === 0) {
    return string;
  }
  return string.charAt(0).toUpperCase() + string.slice(1);
};

// Function to create a display-friendly title from a camelCase/PascalCase string
const formatDisplayTitle = (contextString) => {
  if (!contextString) return "";
  if (contextString === "CommonObjectReference") return "Common Object Reference";
  return contextString.replace(/([A-Z])/g, ' $1').replace(/^ /, '').trim();
};


// Main function to update the AsciiDoc file
const updateAsciiDoc = (filePath) => {
  const currentFileName = path.basename(filePath);
  const currentFileBaseName = path.basename(filePath, ".adoc");
  const commonObjectRefFileName = "CommonObjectReference.adoc";
  const commonObjectRefContext = "CommonObjectReference";

  const adocContext = (currentFileName === commonObjectRefFileName) ? commonObjectRefContext : currentFileBaseName;
  const displayDocumentTitle = formatDisplayTitle(adocContext);

  fs.readFile(filePath, "utf8", (err, data) => {
    if (err) {
      console.error(`Error reading file ${filePath}: ${err}`);
      return;
    }

    const originalLines = data.split("\n");
    let updatedLines = [];
    let preambleAdded = false;

    let inModelsSection = false;
    let inInternalGenerationBlock = false;
    let rawIdFromAnchor = "";
    let skipLinesUntilEndpoints = true; // For boilerplate removal as per user's logic


    for (let i = 0; i < originalLines.length; i++) {
      let line = originalLines[i];
      // Decode HTML entities and unescape quotes for the entire line first
      let decodedLine = entities.decodeHTML(line).replace(/\\"/g, '"');
      const trimmedOriginalLine = line.trim(); // Use original line for exact "== Endpoints" match
      const trimmedDecodedLine = decodedLine.trim();


      // --- Boilerplate Skipping Logic (User's preferred method) ---
      if (skipLinesUntilEndpoints) {
        if (trimmedOriginalLine === "== Endpoints") { // Match exact generator output
          skipLinesUntilEndpoints = false;
          // Add our preamble now that boilerplate is done
          updatedLines.push("// Auto-generated by scripts. Do not edit.");
        updatedLines.push(":_mod-docs-content-type: ASSEMBLY");
        updatedLines.push(`[id="${adocContext}"]`);
        updatedLines.push(`= ${displayDocumentTitle}`);
        updatedLines.push(":toc: macro");
        updatedLines.push(":toc-title:");
        updatedLines.push("");
        updatedLines.push("toc::[]");
        updatedLines.push("");
        updatedLines.push(`:context: ${adocContext}`);
        updatedLines.push("");
        preambleAdded = true;
          continue; // Skip the "== Endpoints" line itself
        }
        continue; // Skip all lines before "== Endpoints"
      }

      // If preamble hasn't been added (e.g. "== Endpoints" was not found, but we are past initial lines)
      if (!preambleAdded && trimmedDecodedLine !== "" && !trimmedDecodedLine.startsWith("//")) {
        // Add preamble if not already done
        updatedLines.push("// Auto-generated by scripts. Do not edit.");
        updatedLines.push(":_mod-docs-content-type: ASSEMBLY");
        updatedLines.push(`[id="${adocContext}"]`);
        updatedLines.push(`= ${displayDocumentTitle}`);
        updatedLines.push(":toc: macro");
        updatedLines.push(":toc-title:");
        updatedLines.push("");
        updatedLines.push("toc::[]");
        updatedLines.push("");
        updatedLines.push(`:context: ${adocContext}`);
        updatedLines.push("");
        preambleAdded = true;
      }

      // Skip all other comments (except the one we add at the very beginning)
      if (trimmedDecodedLine.startsWith("//")) {
          if (updatedLines.length === 0 || !updatedLines[0].startsWith(trimmedDecodedLine)) {
            continue;
          }
      }

      // Skip ifdef::internal-generation[] blocks
      if (trimmedDecodedLine === "ifdef::internal-generation[]") {
          inInternalGenerationBlock = true;
          continue;
      }
      if (trimmedDecodedLine === "endif::internal-generation[]") {
          inInternalGenerationBlock = false;
          continue;
      }
      if (inInternalGenerationBlock) {
          continue;
      }

      // Handle [#models] - this is where definitions start
      if (trimmedDecodedLine.startsWith("[#models]")) {
        inModelsSection = true;
        if (currentFileName === commonObjectRefFileName) {
          updatedLines.push(`[id="models_${commonObjectRefContext}"]`);
          updatedLines.push("== Common object reference");
          updatedLines.push("");
        } else {
          break;
        }
        rawIdFromAnchor = "";
        continue;
      }

      if (inModelsSection && currentFileName !== commonObjectRefFileName) break;

      // Skip model anchors like [#V1GetAlertsCountsResponse] in models section - these are handled by model headings
      if (inModelsSection && trimmedDecodedLine.startsWith("[#") && trimmedDecodedLine.endsWith("]")) {
        continue;
      }

      // Specific cleanup for CommonObjectReference model headings
      if (inModelsSection && currentFileName === commonObjectRefFileName) {
        const modelHeadingMatch = trimmedDecodedLine.match(/^=== _([^_<>]+)_(?: +(.*))?$/);
        if (modelHeadingMatch) {
          const modelName = modelHeadingMatch[1];
          const modelDescription = modelHeadingMatch[2] ? modelHeadingMatch[2].trim() : "";

          // If rawIdFromAnchor was set to this modelName, it means a [#ModelName] was processed.
          let idNeedsAdding = true;
          if (rawIdFromAnchor === modelName) {
            // Check if the last pushed line is already the correct ID.
            if (updatedLines.length > 0 && updatedLines[updatedLines.length - 1] === `[id="${modelName}_${commonObjectRefContext}"]`) {
              idNeedsAdding = false;
            }
          } else if (updatedLines.length > 0 && updatedLines[updatedLines.length - 1] === `[id="${modelName}_${commonObjectRefContext}"]`) {
            // If the ID is already there from a previous generic anchor processing
            idNeedsAdding = false;
          }

          if (idNeedsAdding) {
             updatedLines.push(`[id="${modelName}_${commonObjectRefContext}"]`);
          }
          updatedLines.push(`=== ${modelName}`);
          if (modelDescription) {
            updatedLines.push("");
            updatedLines.push(modelDescription);
          }

          let jsonSubHeadingProcessed = false;
          if (i + 1 < originalLines.length && originalLines[i+1].trim().toUpperCase() === "JSON") {
            if (i + 2 < originalLines.length && originalLines[i+2].trim() === "====") {
                updatedLines.push("");
                updatedLines.push("==== JSON representation");
                i += 2;
                jsonSubHeadingProcessed = true;
            }
          }
          if (!jsonSubHeadingProcessed && (modelDescription || !jsonSubHeadingProcessed)) {
            updatedLines.push("");
          }
          rawIdFromAnchor = "";
          continue;
        }
        if (trimmedDecodedLine.toUpperCase() === "JSON" &&
            i + 1 < originalLines.length && originalLines[i+1].trim() === "====") {
            updatedLines.push("==== JSON representation");
            i++;
            rawIdFromAnchor = "";
            continue;
        }
      }

      // Skip service section headings like [.AlertService] and === AlertService
      if (trimmedDecodedLine.match(/^\[\..*Service\]$/) ||
          (trimmedDecodedLine.match(/^=== .*Service$/) && !inModelsSection)) {
        continue;
      }

      // Skip operation-style anchors like [.alertServiceCountAlerts] - these are CSS classes, not IDs
      if (trimmedDecodedLine.match(/^\[\..*\]$/) && !inModelsSection) {
        continue;
      }

      // Endpoint ID and Heading Processing
      if (!inModelsSection && trimmedDecodedLine.startsWith("[#") && trimmedDecodedLine.endsWith("]")) {
        const idMatch = trimmedDecodedLine.match(/\[#([^\]]+)\]/);
        if (idMatch) {
            rawIdFromAnchor = idMatch[1]; // Store it, will be used by the ==== block
            continue; // Don't add the ID line here, let the operation heading handle it
        }
      }

      if (!inModelsSection && trimmedDecodedLine.match(/^==== /)) { // Operation heading
        let headingTextFromGenerator = trimmedDecodedLine.substring(5).trim();
        let operationNameForDisplay;
        let operationIdForAnchor;

        if (rawIdFromAnchor) {
            let extractedOpId = rawIdFromAnchor;
            const servicePrefix = adocContext;

            if (rawIdFromAnchor.startsWith(servicePrefix + "_")) {
                extractedOpId = rawIdFromAnchor.substring(servicePrefix.length + 1);
            } else if (rawIdFromAnchor.startsWith(servicePrefix) &&
                       rawIdFromAnchor.length > servicePrefix.length &&
                       rawIdFromAnchor[servicePrefix.length] === capitalizeFirstLetter(rawIdFromAnchor[servicePrefix.length] || 'a')) {
                 extractedOpId = rawIdFromAnchor.substring(servicePrefix.length);
            }

            const headingOpPartRaw = headingTextFromGenerator.replace(new RegExp(`^${servicePrefix.replace(/([A-Z])/g, " $1").trim().replace(/\s+/g, '\\s*')}\\s*`, "i"), '').trim();
            const headingOpPart = capitalizeFirstLetter(headingOpPartRaw);

            if (extractedOpId.toLowerCase().endsWith(headingOpPart.toLowerCase()) && extractedOpId !== headingOpPart) {
                 if (extractedOpId.startsWith(servicePrefix) && extractedOpId.substring(servicePrefix.length).toLowerCase() === headingOpPart.toLowerCase()){
                    operationIdForAnchor = headingOpPart;
                 } else {
                    operationIdForAnchor = capitalizeFirstLetter(extractedOpId);
                 }
            } else if (extractedOpId.toLowerCase() === headingOpPart.toLowerCase() || headingOpPartRaw.toLowerCase() === extractedOpId.toLowerCase()) {
                operationIdForAnchor = headingOpPart;
            }
             else {
                 operationIdForAnchor = capitalizeFirstLetter(extractedOpId);
            }
            if (!operationIdForAnchor) operationIdForAnchor = capitalizeFirstLetter(headingTextFromGenerator);

            operationNameForDisplay = operationIdForAnchor;
        } else {
            let cleanedHeadingText = headingTextFromGenerator;
            const serviceNamePattern = new RegExp(`^${adocContext.replace(/([A-Z])/g, " $1").trim().replace(/\s+/g, '\\s*')}\\s*`, "i");
            cleanedHeadingText = headingTextFromGenerator.replace(serviceNamePattern, '').trim();
            if (!cleanedHeadingText) cleanedHeadingText = headingTextFromGenerator;

            operationNameForDisplay = capitalizeFirstLetter(cleanedHeadingText);
            operationIdForAnchor = operationNameForDisplay.replace(/\s+/g, '');
        }

        updatedLines.push(`[id="${operationIdForAnchor}_${adocContext}"]`);
        updatedLines.push(`== ${operationNameForDisplay}`); // Changed from ==== to ==

        rawIdFromAnchor = "";
        continue;
      }

      // General heading processing (H2, H3 from generator) - but skip if it's an operation we already handled
      if (trimmedDecodedLine.match(/^==+ /) && !trimmedDecodedLine.match(/^==== /)) {
        const equalCount = trimmedDecodedLine.match(/^=+/)[0].length;
        let headingText = trimmedDecodedLine.substring(equalCount).trim();

        // Adjust heading levels: reduce by 2 levels when not in models section
        let newEqualCount = equalCount;
        if (!inModelsSection && equalCount > 2) {
          newEqualCount = equalCount - 2;
        }

        updatedLines.push(`${"=".repeat(newEqualCount)} ${headingText}`);
        rawIdFromAnchor = "";
        continue;
      }

      // Process [.Some Title for ID] - this is usually for tables or figures
      if (trimmedDecodedLine.startsWith("[.") && trimmedDecodedLine.endsWith("]")) {
        let idText = trimmedDecodedLine.slice(2, -1).trim();
        const idContextForAnchor = (inModelsSection && currentFileName === commonObjectRefFileName) ? commonObjectRefContext : adocContext;
        updatedLines.push(`[id="${capitalizeFirstLetter(idText.replace(/\s+/g, ''))}_${idContextForAnchor}"]`);
        rawIdFromAnchor = "";
        continue;
      }

      // Process cross-references <<...>>
      if (decodedLine.includes("<<") && decodedLine.includes(">>")) {
        let tempLine = decodedLine;

        // Handle special case for <<Stream_result_of_...>>
        tempLine = tempLine.replace(/<<Stream_result_of_([^>]+)>>/g, (match, content) => {
          return `Stream result of ${content.replace(/_/g, ' ')}.`;
        });

        // Handle special case for <<Next_Tag_...>> and <<Next_available_tag_...>>
        tempLine = tempLine.replace(/<<(Next_Tag__|Next_available_tag__)([^>]+)>>/gi, (match, prefix, content) => {
          let cleanPrefix;
          if (prefix.toLowerCase().includes('available')) {
            cleanPrefix = 'NextAvailableTag';
          } else {
            cleanPrefix = 'NextTag';
          }
          const cleanContent = content.replace(/__/g, '').replace(/_/g, '');
          const combinedText = cleanPrefix + cleanContent;
          return `<<${combinedText}_${adocContext},${combinedText}>>`;
        });

        for (const [key, value] of Object.entries(specificReplacements)) {
          tempLine = tempLine.replace(new RegExp(key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), "g"), value);
        }

        tempLine = tempLine.replace(/<<\s*([^,>]+?)(?:_([^_<>]+))?\s*(?:,\s*([^>]+?))?\s*>>/g, (match, target, _ignore, text) => {
          const linkTarget = target.trim();
          const linkText = text ? text.trim() : linkTarget;
          const isLikelyModel = /^[A-Z][a-zA-Z0-9_]*$/.test(linkTarget);

          if (currentFileName !== commonObjectRefFileName && isLikelyModel) {
            return `xref:../${commonObjectRefContext}/${commonObjectRefFileName}#${linkTarget}_${commonObjectRefContext}[${linkText}]`;
          } else if (currentFileName === commonObjectRefFileName && isLikelyModel) {
            return `<<${linkTarget}_${commonObjectRefContext},${linkText}>>`;
          } else {
            return `<<${linkTarget}_${adocContext},${linkText}>>`;
          }
        });
        updatedLines.push(tempLine);
        rawIdFromAnchor = "";
        continue;
      }

      // Push other lines if preamble has been added and line is not empty or not a duplicate blank line
      if(preambleAdded && (trimmedDecodedLine !== "" || (updatedLines.length > 0 && updatedLines[updatedLines.length-1].trim() !== "") )) {
        updatedLines.push(decodedLine);
      }

      if (preambleAdded) {
          rawIdFromAnchor = "";
      }
    }

    // Remove trailing blank lines
    while (updatedLines.length > 0 && updatedLines[updatedLines.length - 1].trim() === "") {
        updatedLines.pop();
    }

    const updatedContent = updatedLines.join("\n") + "\n";
    fs.writeFile(filePath, updatedContent, "utf8", (writeErr) => {
      if (writeErr) {
        console.error(`Error writing file ${filePath}: ${writeErr}`);
      }
    });
  });
};

const mainFilePath = process.argv[2];
if (!mainFilePath) {
  console.error("Please provide the AsciiDoc file path as an argument.");
  process.exit(1);
}

updateAsciiDoc(mainFilePath);
